### ISSUE TITLE
Source code highlighting

### ISSUE THREAD

**Issue by jcubic** [dephraiim/termd#1]
I have a project [prism-cli](https://github.com/jcubic/prism-cli) that use [PrismJS](https://prismjs.com/) to render source code in terminal. Maybe you can use it with termd.

**Comment by ephraimduncan** [comment]
I have syntax highlighting available with `cardinal` but it's for `js`,`ts`,`jsx`,`tsx` and `json` files so if prism-cli supports other languages, I'll be happy to add it.

**Comment by jcubic** [comment]
prism-cli is just tiny wrapper over PrismJS that support lot of languages. Here is the list: https://prismjs.com/#supported-languages

**Comment by ephraimduncan** [comment]
That's a lot of languages. Can I use `prism-cli` as a library?. You said it's a cli application but I need to use it as a library.

**Comment by jcubic** [comment]
Yes, you can import it and use highlight function. If you will not like the colors you can customize them. Here is relevant section in README https://github.com/jcubic/prism-cli#nodejs-module

**Comment by ephraimduncan** [comment]
Okay.. I'll make a PR and get to you when I'm done.

**Comment by jcubic** [comment]
BTW: very useful project.

**Comment by jcubic** [comment]
What I would change is the name of the executable, it's hard to remember. Maybe change it to `md` from Markdown, I think I will use alias like this. The name of the executable don't need to be the same as project name.

**Comment by ephraimduncan** [comment]
I'd love to change the executable name on but it's hosted on npm and all the short and simple names are taken. You can add it as an alias in your `.bashrc`. if you also get a simple name that's not taken, please tell me then I'll change the name.

**Comment by jcubic** [comment]
I don't think you need to change the name of the package, you can just name the executable. prism-cli have name prism even that there is a package named like that.

You can try to change:
```
   "bin": {
        "md": "index.ts"
    },
```

update version and test with `npm publish --dry-run` and see if it fail.

**Comment by ephraimduncan** [comment]
`npm publish --dry-run` run without any errors.

**Comment by ephraimduncan** [comment]
Hello @jcubic, I have a [branch](https://github.com/dephraiim/termd/tree/prism) with  syntax highlighting. It works fine but for some languages, it returns plain white text. 

I checked and it turns out, you do not have a color allocation for those tokens which returns plain white text. I tried to use the `.prismrc` and it turns out it only for the command line.

Graying the text as it was before will tell much difference that the white text so I am asking, is there that I can add the `.prismrc` using the library?

If there isn't, we can check for ANSI code after passing it through the `highlight` from `prism-cli` and If there isn't one, we can just gray it.

**Comment by jcubic** [comment]
Will check it probably don't load the languages. if it only works for css,html,js then that's probably it. Will check when I have time why it don't show other languages, maybe will find some time tomorrow morning.

As for .prismrc it's not needed because you can pass the object with mapping token => ANSI code to the function, it's simpler. If you want you can load a file and pass the value to the function. main function have everything CLI have.

You can create the same palette that you were using with old library. to find the token names you can open CSS file of PrismJS and check the classes. https://github.com/PrismJS/prism/blob/master/themes/prism.css

**Comment by ephraimduncan** [comment]
It works for js but not HTML and CSS

**Comment by jcubic** [comment]
I think that there are simple missing default tags, for css. becasue comments how up. for HTML it's probbaly the same. I think I would need to add default colors but you can do the same in your project without the need to upgrade dependency.

**Comment by ephraimduncan** [comment]
I have pushed a commit. Check the last commit in the branch to confirm it for me.

**Comment by jcubic** [comment]
It looks good. I have a question in package.json there are no `ts-node` as dependency and it don't work when I've installed using `npm install -g .` I'm not sure how I've tested this program before.

**Comment by ephraimduncan** [comment]
I have `ts-node` installed globally when developing so I will add it to the readme. But for `npm`, I have all a `build.js` file that compiles the typescript to javascript into a `dist` folder then I ran  `npm publish` from the build folder.

**Comment by ephraimduncan** [comment]
@jcubic, I hope I can close it now.

**Comment by jcubic** [comment]
yes, you can close the issue.Good job.

**Comment by ephraimduncan** [comment]
Thanks.
