### ISSUE TITLE
Releases & Release notes

### ISSUE THREAD

**Issue by AdrienLemaire** [dephraiim/termd#7]
Hi, and thanks for your project. 
Can you create github releases following semver with release notes ?
That'd be much appreciated, as I could watch for the releases and upgrade my package accordingly.

**Comment by ephraimduncan** [comment]
Hello @AdrienLemaire. Thanks for the suggestion. I'm working on it.

**Comment by ephraimduncan** [comment]
I have created various releases and tag at the major changes. You can check it at the [releases](https://github.com/dephraiim/termd/releases) page.
